name: Monthly Wordle Update

on:
  workflow_dispatch:

  schedule:
    - cron: '0 18 1 * *'

jobs:
  update-wordle-solutions:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq hugo

      - name: Make script executable
        run: chmod +x ./.github/wordler.sh

      - name: Run Wordle generator script
        run: ./.github/wordler.sh

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "posts: Update Wordle solutions for the month"
          git push
